YLN_DB_PATH = "c:/Users/Kojo Adu/source/repos/YLN/app/data/yln.db"
YLN_SUPER_ADMIN_EMAIL = "admin@yln.local"
YLN_SUPER_ADMIN_PASSWORD = "admin1234"
YLN_SMTP_HOST = ""
YLN_SMTP_PORT = 587
YLN_SMTP_USER = ""
YLN_SMTP_PASS = ""
YLN_SMTP_FROM = "noreply@yln.local"
YLN_SMTP_TLS = true
